// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eocnqdjslwwtoostqxng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvY25xZGpzbHd3dG9vc3RxeG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjgyNjIsImV4cCI6MjA2NDU0NDI2Mn0.oKdvynY3e-uUK_e0tiVzwApAG0mAQi1CHqC5UKe1AIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);